### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lso033c** [ahmedre/prayertimes-kmp#18]
could you explain why `DispatchQueue.main.async` is used? , why ` withContext(Dispatchers.IO)` is not enough 
``` import Foundation
import shared

class PrayerTimesRespository: ObservableObject {
  @Published var result: SalahTimes? = nil
  private let salahCalculator = SalahCalculator()
  
  func search(name: String) {
    self.salahCalculator.prayerTimes(placeName: name,
                                     completionHandler:
                                      { result, error in
      if let actualResult = result {
        DispatchQueue.main.async {
          self.result = actualResult
        }
      }
    })
  }
} ```

**Comment by ahmedre** [comment]
If I were consuming this on mobile, I'd want the results to come back on the main thread since we typically only update the ui from a main thread.

**Comment by lso033c** [comment]
what is about running self.salahCalculator.prayerTimes on withContext(Dispatchers.Main ) somehow is it enough for IOS?

**Comment by ahmedre** [comment]
that would mean in the kmp library itself, i would need to set the output to be on the main dispatcher, which might not make sense for non-mobile applications. the caller should determine the coroutine they want to receive the information on. in this case, i want Swift to set the value of this ui variable in the ui thread.

**Comment by ahmedre** [comment]
although now that i think about it, it's possible that the explicit switch to the main dispatch queue isn't necessary given that the callback should occur on the calling thread.
