### ISSUE TITLE
hosting kmm model in standalone repo

### ISSUE THREAD

**Issue by periva101** [ahmedre/prayertimes-kmp#5]
can you explain how to host the kmm model in the standalone repo , and how to debug that module with android code base

**Comment by ahmedre** [comment]
if you just want prayer calculations, you'll use the `adhan` library directly without using this code in your android application - a good example to see is [here](https://github.com/batoulapps/adhan-java/tree/kotlin_multiplatform/samples) for the Kotlin version, or [here](https://github.com/batoulapps/adhan-java/tree/master/samples) for the Java version.

from there, you can easily attach a debugger to your code and use it. if you want to use this code specifically with its Kotlin Multiplatform support, just clone the repository and open the Android folder in your version of Android Studio. You can put a breakpoint at any point to debug.
