### ISSUE TITLE
kmm debugging issue 

### ISSUE THREAD

**Issue by periva101** [ahmedre/prayertimes-kmp#9]
assalamu alaikum
how are you brother, 
may Allah bless you
I watched your kmm videos with the kotlin team and touch lab, and all of them are super great, please do more of those videos you have a lot to share. 

my question is about KMM bugs, you know in android it is super easy to debug and the error is very clear, however in ios errors are wried, and no pointer on the line causing the issue,
eg. 
->  0x10eed9038 <+72>: jmp    0x10eed903a               ; <+74> at CoroutineExceptionHandlerImpl.kt:14:2

please any ideas or suggestions on this topic

**Comment by ahmedre** [comment]
wa3laikum alsalam,
sorry I somehow missed this message from long ago - you might want to look at the TouchLab plugin - https://github.com/touchlab/xcode-kotlin, which might help.
walsalam 3alaikum
